# Use root/example as user/password credentials
version: '3.1'

services:
  GesSous:
    container_name: GesSous
    image: franky/gessous:v1
    depends_on:
      - database
    ports:
      - 8091:8090
    networks:
      - gessous-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/gessous
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  database:
    image: mariadb:11.1
    restart: always
    networks:
      - gessous-network
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    networks:
      - gessous-network
    ports:
      - 8082:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    networks:
      - gessous-network
    ports:
      - 9081:80
      - 9025:25
volumes:
  init:
networks:
  gessous-network :

